### ISSUE TITLE
难道我只能等？

### ISSUE THREAD

**Issue by sstarfish** [cornjosh/Aminer#14]
![DSC_0162](https://user-images.githubusercontent.com/82608047/117958188-5c75a680-b34d-11eb-92fc-588b356b4857.JPG)

是要等伺服器回应我？
我需要重开吗，还是他会自动重新连接？

**Comment by cornjosh** [comment]
似乎是网络问题或者矿池问题。这不是脚本的问题。具体问题请咨询c3pool😬
