### ISSUE TITLE
机器不使用内存算力底下问题

### ISSUE THREAD

**Issue by lxzcl** [cornjosh/Aminer#16]
机器是4G内存用xmrig直接在tm上编译然后运行，使用内存算力能达到240H，用这个脚本反而不使用内存，机器cpu是骁龙660
![QQ图片20210516125444](https://user-images.githubusercontent.com/41499707/118385922-ebccd380-b645-11eb-93d5-8430d645b172.jpg)

**Comment by lxzcl** [comment]
这是我使用的命令
bash <(curl -fsSL git.io/aminer) -o pool.supportxmr.com:3333 -u 42aaNhHtTjC5TnSbL6nrDGLFjR5eLT6gbeLzLgY6K5XifyUrKM6YGPTU55zuaFrLFdaxW2ciM5ZUFcUUsVF3bubjRuXKfsV -p phone -d 0

**Comment by lxzcl** [comment]
在c3pool矿池中只有700+算力，相比于625的1kH是不是有点少了

**Comment by cornjosh** [comment]
使用内存是指开启hugepage还是初始化randomX数据集用的2G内存？

**Comment by lxzcl** [comment]
好吧我没用过混合挖的矿池，是算法问题，但是我的骁龙660放冰箱挖c3pool都达不到1K的算力，是现在奖励比例更改了么？主页的基准是不是有些夸大了，我只能达到600h左右。

**Comment by cornjosh** [comment]
> 好吧我没用过混合挖的矿池，是算法问题，但是我的骁龙660放冰箱挖c3pool都达不到1K的算力，是现在奖励比例更改了么？主页的基准是不是有些夸大了，我只能达到600h左右。

在忙其他事情许久没更新了，刚刚看了一下骁龙625是800+h，略有下降但在浮动范围内。CPU算力不是型号越高就越快的，骁龙675仅600h左右

另外，欢迎发起PR来更新你的算力供他人参考，谢谢
