### ISSUE TITLE
RedMi 5 Plus 的骁龙625 仅有38.17 H/S

### ISSUE THREAD

**Issue by VigtigsteL** [cornjosh/Aminer#17]
RedMi 5 Plus 的骁龙625 速率仅有38.17 H/S
完全达不到作者说的速率1K
请问是哪里出了问题

![Snipaste_2021-05-17_20-04-51](https://user-images.githubusercontent.com/60757020/118485580-32f0bc80-b74b-11eb-8360-6ddb3bf29d8b.png)

![20210517201145](https://user-images.githubusercontent.com/60757020/118486544-536d4680-b74c-11eb-93bc-7a49d96a9cf4.png)

**Comment by cornjosh** [comment]
没有问题，保证稳定的网络连接和良好的散热环境，c3pool为多币种机枪池，raw算力不同于pay算力，请仔细阅读项目README。具体情况咨询矿池方
