### ISSUE TITLE
确定被gfk拦截，换VPN后又出现问题

### ISSUE THREAD

**Issue by coco9913** [cornjosh/Aminer#18]
输入bash <(curl -fsSL git.io/aminer) -u xxxx后，显示curl: (56) Recv failure: Connection reset by peer

**Comment by coco9913** [comment]
确定了，是被gfw拦截

**Comment by coco9913** [comment]
![Screenshot_2021-05-18-20-40-32-62_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/84388293/118653314-f93ab700-b819-11eb-85c3-bbf5274b79fa.jpg)

**Comment by cornjosh** [comment]
链接不上中国科技大学镜像服务器，网络问题
