### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by zhang20212021** [cornjosh/Aminer#3]
![Screenshot_20210419-023132](https://user-images.githubusercontent.com/82776308/115156808-b7064480-a0b8-11eb-9f8f-82b4bf4a6050.jpg)
![Screenshot_20210419-024336](https://user-images.githubusercontent.com/82776308/115156899-3267f600-a0b9-11eb-9bba-c15afa585a90.jpg)
运行程序时报错，是服务器端的问题吗？

**Comment by cornjosh** [comment]
Connection reset by peer ，网络问题，被gfw拦截了吧
