### ISSUE TITLE
編譯失敗

### ISSUE THREAD

**Issue by top9628** [cornjosh/Aminer#7]
![Screenshot_2021-05-03-11-55-32-444_com termux](https://user-images.githubusercontent.com/83566639/116842837-8a057600-ac10-11eb-9d21-2a991d227a45.jpg)
![Screenshot_2021-05-03-13-08-08-374_com termux](https://user-images.githubusercontent.com/83566639/116842860-a0abcd00-ac10-11eb-8770-891e33974de0.jpg)

**Comment by FuXiangGit** [comment]
遇到同样的问题，能否提供个解决办法，谢谢

**Comment by cornjosh** [comment]
问题由 xmrig-c3 引入，现已修复，请完全删除之前的残留文件后重新安装，感谢 @KawaiiZapic
