### ISSUE TITLE
启动失败

### ISSUE THREAD

**Issue by coutliuxing** [cornjosh/Aminer#9]
大佬，启动失败了啊
![image](https://user-images.githubusercontent.com/8907930/117533936-dfcb8b00-b021-11eb-8532-7dbd1ad453b1.png)
![image](https://user-images.githubusercontent.com/8907930/117533955-f245c480-b021-11eb-9b38-fc0854cfe75d.png)

**Comment by jchuang1977** [comment]
可能XMIRG編譯失敗了....

**Comment by coutliuxing** [comment]
这~应该怎么办呢？

**Comment by jchuang1977** [comment]
會手動編譯的話, 你在cmake 階段要加上下面的參數
you can use( cmak -DWITH_CN_GPU=OFF .. )
In that case u can't use cn/gpu algo

**Comment by coutliuxing** [comment]
会点点，但这里只有.sh文件

**Comment by cornjosh** [comment]
问题由 xmrig-c3 引入，现已修复，请完全删除之前的残留文件后重新安装，感谢 @KawaiiZapic
